-- MySQL Workbench Synchronization
-- Generated: 2023-10-19 12:21
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: formacio

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `mydb`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `mydb`.`ULLERES` 
DROP FOREIGN KEY `fk_ULLERES_EMPLEAT1`,
DROP FOREIGN KEY `fk_ULLERES_PROVEIDOR1`;

ALTER TABLE `mydb`.`EMPLEAT_has_CLIENT` 
DROP FOREIGN KEY `fk_EMPLEAT_has_CLIENT_CLIENT1`;

ALTER TABLE `mydb`.`PROVEIDOR` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `mydb`.`ULLERES` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `graduacio` `graduacio` DECIMAL(2) NOT NULL ,
CHANGE COLUMN `preu` `preu` DECIMAL(2) NOT NULL ;

ALTER TABLE `mydb`.`CLIENT` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `mydb`.`EMPLEAT` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE `mydb`.`EMPLEAT_has_CLIENT` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
DROP INDEX `fk_EMPLEAT_has_CLIENT_CLIENT1` ;
;

ALTER TABLE `mydb`.`ULLERES` 
ADD CONSTRAINT `fk_ULLERES_EMPLEAT1`
  FOREIGN KEY (`EMPLEAT_ID_Client` , `EMPLEAT_id_empleat`)
  REFERENCES `mydb`.`EMPLEAT` (`ID_Client` , `id_empleat`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_ULLERES_PROVEIDOR1`
  FOREIGN KEY (`PROVEIDOR_id_proveidor`)
  REFERENCES `mydb`.`PROVEIDOR` (`id_proveidor`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `mydb`.`EMPLEAT_has_CLIENT` 
DROP FOREIGN KEY `fk_EMPLEAT_has_CLIENT_EMPLEAT1`;

ALTER TABLE `mydb`.`EMPLEAT_has_CLIENT` ADD CONSTRAINT `fk_EMPLEAT_has_CLIENT_EMPLEAT1`
  FOREIGN KEY (`EMPLEAT_ID_Client` , `EMPLEAT_id_empleat`)
  REFERENCES `mydb`.`EMPLEAT` (`ID_Client` , `id_empleat`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT `fk_EMPLEAT_has_CLIENT_CLIENT1`
  FOREIGN KEY (`CLIENT_recomana_IDClient`)
  REFERENCES `mydb`.`CLIENT` (`recomana_IDClient`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
